[workspace]
resolver = "2"
members = [
    "rollup-interface",
    "adapters/risc0",
    "adapters/celestia",
    "examples/const-rollup-config",
    "examples/demo-stf",
    "examples/demo-simple-stf",
    "examples/demo-rollup",
    "examples/demo-nft-module",
    "full-node/db/sov-db",
    
    "module-system/sov-modules-stf-template",
    "module-system/sov-modules-macros",
    "module-system/sov-state",
    "module-system/sov-modules-api",
    "module-system/utils/sov-first-read-last-write-cache",
    "module-system/module-implementations/sov-accounts",
    "module-system/module-implementations/sov-bank",
    "module-system/module-implementations/sov-prover-incentives",
    "module-system/module-implementations/sov-sequencer-registry",
    "module-system/module-implementations/module-template",
    "module-system/module-implementations/sov-swap",
    "module-system/module-implementations/examples/sov-value-setter",
    "module-system/module-implementations/examples/sov-election",
    "module-system/module-implementations/integration-tests",
]
exclude = [
    "examples/demo-prover",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Sovereign Labs <info@sovereign.xyz>"]
homepage = "sovereign.xyz"
publish = false
repository = "https://github.com/sovereign-labs/sovereign-sdk"
rust-version = "1.66"

[workspace.dependencies]
# Dependencies maintained by sovereign
jmt = "0.6.0"

# External dependencies
anyhow = "1.0.68"
borsh = { version = "0.10.3", features = ["rc", "bytes"] }
byteorder = "1.4.3"
bytes = "1.2.1"
hex = "0.4.3"
once_cell = "1.10.0"
prometheus = { version = "0.13.3", default-features = false }
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.8"
rayon = "1.5.2"
rocksdb = { version = "0.19.0", features = ["lz4"] }
serde = { version = "1.0.137", features = ["derive", "rc"] }
serde_json = { version = "1.0" }
sha2 = "0.10.6"
thiserror = "1.0.38"
tiny-keccak = "2.0.2"
tracing = "0.1.37"
bech32 = "0.9.1"
derive_more = "0.99.11"
clap = { version = "4.2.7", features = ["derive"] }
toml = "0.7.3"
jsonrpsee = "0.16.2"
